### ISSUE TITLE
React does not recognize the `portalContainer` prop on a DOM element

### ISSUE THREAD

**Issue by baerkins** [daybrush/moveable#409]
## Environments
* Framework name: React
* Framework version: 17.0.1
* Moveable Component version: 0.26.0

## Description

Not sure if I am doing something wrong, but I get this error whenever I initialize the `<Moveable />` component:

```
Warning: React does not recognize the `portalContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `portalcontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Styled (http://localhost:3000/static/js/0.chunk.js:16622:45)
    at MoveableManager (http://localhost:3000/static/js/0.chunk.js:56915:43)
    at Moveable (http://localhost:3000/static/js/0.chunk.js:58544:38)
	...
```

The Moveable React component is setup as:
```
<Moveable
  target={document.getElementById('tile-0')}
  container={null}
  draggable={true}
  origin={false}
  rotatable={true}
  resizable={false}
/>
```

If you need any other information, let me know!

**Comment by daybrush** [comment]
@baerkins 

0.26.1 is released. Check it again.

**Comment by baerkins** [comment]
Awesome, thanks for the help!!
